#!/usr/bin/env bash

DEFAULT_PORT=56789

# Parse port from .vscode/launch.json if we're inside a vscode terminal.
if [[ "$TERM_PROGRAM" == "vscode" ]] && [[ -f ".vscode/launch.json" ]]; then
	port="$(jq -r '
	  .configurations[]
	  | select(.type == "debugpy")
	  | .connect.port // empty
	  ' .vscode/launch.json 2>/dev/null || printf "$DEFAULT_PORT")"
else
	port="$DEFAULT_PORT"
fi

# Start debugger and wait for client to attach. The envvar silences a warning
# about frozen modules.
PYDEVD_DISABLE_FILE_VALIDATION=1 python -m debugpy --listen "$port" --wait-for-client "$@"

