#!/usr/bin/env sh

# Part of the disgusting hack to get commandline driven debugging up and
# running in vscode. Requires xdotool, xprop, debugpy.

# Check whether vscode is the currently active window
wid="$(xdotool getactivewindow)"
wtype="$(xprop -id "$wid" -notype WM_CLASS | tr -d ' "' | cut -d= -f2)"
if [ ! "$wtype" = "code,Code" ]; then
	echo "Not inside VSCode. Abort." >&2
	exit 1
fi

# Time emulated keypress with xdotool
(sleep 1 && xdotool key ctrl+shift+F5) &
keypress_pid="$!"

# Start debugger and wait for client to attach. The envvar silences a warning
# about frozen modules.
PYDEVD_DISABLE_FILE_VALIDATION=1 python -m debugpy --listen 56789 --wait-for-client "$@"

# If the debugger fails to start (missing file, wrong arguments), we prevent
# the keypresses from occuring by killing the background process.
kill "$keypress_pid" 2>/dev/null
