#!/usr/bin/env -S sh -e

usage() {
	name="$(basename "$0")"
	cat <<EOF
Spawn a new terminal with an interactive zsh session in the working
directory of the currently selected window.

Usage:
	$name
EOF
}

termcwd() {
	props="$(xprop -notype -id "$(xdotool getwindowfocus)")"
	if echo "$props" | grep -qF "_NET_WM_PID"; then
		pid="$(echo "$props" | grep "^_NET_WM_PID" | cut -d= -f2 | tr -d ' ')"
		echo "cd $(realpath /proc/$pid/cwd)" | zshxi "$TERMINAL" &
	else
		$TERMINAL &
	fi
}

case "$1" in
	-h|--help) usage ;;
	"") termcwd ;;
	*) usage; exit 1 ;;
esac
