#!/usr/bin/env sh

usage() {
	name="$(basename "$0")"
	cat <<EOF
Check a terminal's available font effects and color capabilities. Produces
output which utilizes terminal escape codes to control font and color. Use
to check your terminal's feature coverage.

Usage:
	(1) $name font - font effects
	(2) $name ansi - 8-bit ansi colors
	(3) $name true - 24-bit true color
EOF
}

font() {
	echo -e "\033[1mbold\033[22m"
	echo -e "\033[2mdim\033[22m"
	echo -e "\033[3mitalic\033[23m"
	echo -e "\033[4munderline\033[24m"
	echo -e "\033[4:1mthis is also underline (new in 0.52)\033[4:0m"
	echo -e "\033[21mdouble underline (new in 0.52)\033[24m"
	echo -e "\033[4:2mthis is also double underline (new in 0.52)\033[4:0m"
	echo -e "\033[4:3mcurly underline (new in 0.52)\033[4:0m"
	echo -e "\033[5mblink (new in 0.52)\033[25m"
	echo -e "\033[7mreverse\033[27m"
	echo -e "\033[8minvisible\033[28m <- invisible (but copy-pasteable)"
	echo -e "\033[9mstrikethrough\033[29m"
	echo -e "\033[53moverline (new in 0.52)\033[55m"
	
	echo -e "\033[31mred\033[39m"
	echo -e "\033[91mbright red\033[39m"
	echo -e "\033[38:5:42m256-color, de jure standard (ITU-T T.416)\033[39m"
	echo -e "\033[38;5;42m256-color, de facto standard (commonly used)\033[39m"
	echo -e "\033[38:2::240:143:104mtruecolor, de jure standard (ITU-T T.416) (new in 0.52)\033[39m"
	echo -e "\033[38:2:240:143:104mtruecolor, rarely used incorrect format (might be removed at some point)\033[39m"
	echo -e "\033[38;2;240;143;104mtruecolor, de facto standard (commonly used)\033[39m"
	
	echo -e "\033[46mcyan background\033[49m"
	echo -e "\033[106mbright cyan background\033[49m"
	echo -e "\033[48:5:42m256-color background, de jure standard (ITU-T T.416)\033[49m"
	echo -e "\033[48;5;42m256-color background, de facto standard (commonly used)\033[49m"
	echo -e "\033[48:2::240:143:104mtruecolor background, de jure standard (ITU-T T.416) (new in 0.52)\033[49m"
	echo -e "\033[48:2:240:143:104mtruecolor background, rarely used incorrect format (might be removed at some point)\033[49m"
	echo -e "\033[48;2;240;143;104mtruecolor background, de facto standard (commonly used)\033[49m"
	
	echo -e "\033[21m\033[58:5:42m256-color underline (new in 0.52)\033[59m\033[24m"
	echo -e "\033[21m\033[58;5;42m256-color underline (new in 0.52)\033[59m\033[24m"
	echo -e "\033[4:3m\033[58:2::240:143:104mtruecolor underline (new in 0.52) (*)\033[59m\033[4:0m"
	echo -e "\033[4:3m\033[58:2:240:143:104mtruecolor underline (new in 0.52) (might be removed at some point) (*)\033[59m\033[4:0m"
	echo -e "\033[4:3m\033[58;2;240;143;104mtruecolor underline (new in 0.52) (*)\033[59m\033[4:0m"
}

ansi() {
	for ii in $(seq 0 255); do
		echo -e "\033[38;5;"$ii"mIs this the real life?\033[m"
	done
}

true() {
	awk 'BEGIN{
	s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
	for (colnum = 0; colnum<77; colnum++) {
		r = 255-(colnum*255/76);
		g = (colnum*510/76);
		b = (colnum*255/76);
		if (g>255) g = 510-g;
		printf "\033[48;2;%d;%d;%dm", r,g,b;
		printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
		printf "%s\033[0m", substr(s,colnum+1,1);
	}
	printf "\n";
}'
}

case $1 in
	font) font ;;
	ansi) ansi ;;
	true) true ;;
	-h|--help) usage ;;
	*) usage; exit 1 ;;
esac
